#docker compose file
version: '2'
services:
  zone_db:
    image: rethinkdb:latest
    ports:  
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
  publisher:
    build: .
    environment:
      - AUTH0_CLIENT_SECRET=-QZB4_uxwVfzgDieFPdzt_ItmN74bplBHYLeE-v049nakX1ada3N2xziJeOMNthF
      - AUTH0_CLIENT_ID=cO02S01qm4vmAp2jhUtuLI4iAfQgXNx4
      - PORT=8089
   
    ports:
      - "9004:9004"
    command:  node app
    depends_on:
      - zone_db