swagger: "2.0"
info:
  description: "connection services API"
  version: "1.0"
  title: "TL plan services API"
basePath: "/v2/components/plan-service"
schemes:
- "http"
# format of bodies a client can send (Content-Type)
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: Authorization
paths:  
  /zone/{zoneId}/plans:
    get:
      tags:
      - "plans "
      summary: "Get all plans"
      description: "Get all plans"
      operationId: "getAllplansForZone"
      produces:
      - "application/json"
      parameters:
      - name: "zoneId"
        in: "path"
        description: "zone id"
        required: true
        type: "string"
      responses:
        200:
          description: "A list of plans."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/plans"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "planService"
    
    post:
      tags:
      - "plans"
      summary: "Creates a plan."
      description: "Creates a plan."
      operationId: "createplan"
      security: 
        - UserSecurity: [] 
      produces:
      - "application/json"
      parameters:    
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/plans"
      - name: "zoneId"
        in: "path"
        description: "zone id"
        required: true
        type: "string"
      responses:
        200:
          description: "plan Details"
          schema:
            type: "object"
            properties: {}
        400:
          description: "Error creating a new plan"
        default:
          description: "Unexpected error"
    
      x-swagger-router-controller: "planService"
  /zone/plans:
    get:
      tags:
      - "plans "
      summary: "Get all plans"
      description: "Get all plans"
      operationId: "getAllplans"
      security: 
        - UserSecurity: []
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of plans."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/plans"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "planService"
  /zone/{zoneId}/plans/{planId}:
    get:
      tags:
      - "plan by plan id"
      summary: "Get plan"
      description: "Get plan by planId"
      operationId: "getplanById"
      security: 
        - UserSecurity: []
      parameters:
        - name: planId
          in: path
          description: planId
          required: true
          type: string
        - name: "zoneId"
          in: "path"
          description: "zone id"
          required: true
          type: "string"
      produces:
      - "application/json"
      responses:
        200:
          description: "A json of type for given planId."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/plans"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "planService" 
    delete:
      tags:
      - "Delete type by plan id"
      summary: "delete plan"
      description: "delete plan by planId"
      operationId: "deleteplan"
      security: 
        - UserSecurity: []
      parameters:
        - name: planId
          in: path
          description: planId
          required: true
          type: string
        - name: "zoneId"
          in: "path"
          description: "zone id"
          required: true
          type: "string"
      produces:
      - "application/json"
      responses:
        200:
          description: "deleted plan."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/plans"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "planService"     
    put:
      tags:
      - "update plan by plan id"
      summary: "updates a plan."
      description: "updates a plan."
      operationId: "updateplan"
      security: 
        - UserSecurity: []
      parameters:
        - name: planId
          in: path
          description: planId
          required: true
          type: string 
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/plans"
        - name: "zoneId"
          in: "path"
          description: "zone id"
          required: true
          type: "string"
      produces:
      - "application/json"
      responses:
        200:
          description: "update plan."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/plans"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "planService" 
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:  
  plans:
    type: "object"    
